import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";

const prisma = new PrismaClient();

const TODOS_CLIENTES = [
  {
    contratante: "3MJ PARTICIPAÇÕES LTDA",
    cpfCnpj: "26.262.219/0001-52",
    telefone: null,
    email: null,
    endereco: "Avenida Getúlio Vargas",
    bairro: "Centro",
    cep: "38400-299",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "ADRIANO FERNANDES FELIX",
    cpfCnpj: "055.106.586-90",
    telefone: "3499674-8089",
    email: null,
    endereco: "RUA ANTÔNIO LUIS DE MENDOÇA Nº256",
    bairro: "JD IPANEMA",
    cep: null,
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "CENTRO DE TREINAMENTO BASE SPORTING CLUBE LTDA",
    cpfCnpj: "13.631.663/0001-56",
    telefone: "3499977-3949",
    email: null,
    endereco: "Avenida Zulma Costa Abdala",
    bairro: "Mansões Aeroporto",
    cep: "38406-406",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "CN PISO FORTE LTDA",
    cpfCnpj: "51.111.445/9000-15",
    telefone: "3499976-1528",
    email: null,
    endereco: "Rua Professor Ciro de Castro Almeida Nº1905",
    bairro: "Custódio Pereira",
    cep: "38405-250",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "Exclusive Residence Participações SPE LTDA",
    cpfCnpj: "55.887.108/0001-67",
    telefone: "3432553139",
    email: null,
    endereco: "Rua José de Oliveira Pinto",
    bairro: "Tubalina",
    cep: "38412-098",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "KAIRES MONTEIRO LTDA",
    cpfCnpj: "08.602.731/0001-19",
    telefone: "3499977-3614",
    email: null,
    endereco: "RUA HORACIO PEREIRA MENDES Nº223",
    bairro: "PLANALTO",
    cep: "38410-273",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "MASCOTE ENGENHARIA E PARTICIPAÇÕES LTDA",
    cpfCnpj: "02.669.454/0001-85",
    telefone: null,
    email: null,
    endereco: "AV GETULHO VARGAS Nº275",
    bairro: "CENTRO",
    cep: "38400-299",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "MINAS MIX CONSTRUÇÕES E INCORPORAÇÕES LTDA",
    cpfCnpj: "05.453.446/0001-95",
    telefone: null,
    email: null,
    endereco: "RUA MANOEL MADRUGA Nº50",
    bairro: "GAVEA SUL",
    cep: "38425-367",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "MORAES DURANTE CONSTRUTORA LTDA",
    cpfCnpj: "54.275.015/0001-91",
    telefone: "3499682-8546",
    email: null,
    endereco: "RUA ALBERTINO SILVA/ CASA 2 Nº140",
    bairro: "ROOSEVELT",
    cep: "38401-220",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "PORCELANATARIA PREMIUM LTDA",
    cpfCnpj: "49.325.660/0001-31",
    telefone: "3499208-2446",
    email: null,
    endereco: "RUA DO PINTOR Nº67",
    bairro: "PLANALTO",
    cep: "38413-198",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "SOARES MORAES CONSTRUTORA E INCORPORADORA",
    cpfCnpj: "12.333.011/0001-72",
    telefone: "343214-2747",
    email: null,
    endereco: "RUA ITUIUTABA Nº60",
    bairro: "APARECIDA",
    cep: null,
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "SOUZA PINTURAS E REVESTIMENTOS",
    cpfCnpj: "29.909.394/0001-87",
    telefone: "3499861-4980",
    email: null,
    endereco: "RUA DAS EMAS Nº17",
    bairro: "MORUMBI",
    cep: "38407-251",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "Brasiel Arquitetura e Construção LTDA",
    cpfCnpj: "37.336.347/0001-10",
    telefone: "3499632-2552",
    email: null,
    endereco: "Rua José Antônio Domingues N°217",
    bairro: "Novo Mundo",
    cep: "38409-061",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "Maurício Antônio pimenta",
    cpfCnpj: "828.418.536-91",
    telefone: "3246707-4403",
    email: null,
    endereco: "Rua Ernestina Mota Rodrigues 400",
    bairro: "Santa Luzia",
    cep: "38408-690",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "José Arnaldo de sousa",
    cpfCnpj: "049.976.633-44",
    telefone: "3499795-5084",
    email: null,
    endereco: "rua 2 número 5",
    bairro: "mana",
    cep: null,
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "Fernando Alves Fernandes",
    cpfCnpj: "097.333.466-59",
    telefone: "3499280-4152",
    email: null,
    endereco: "Rua capivara N351",
    bairro: "residencial pequis",
    cep: null,
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "ALLINE MENDES FERREIRA",
    cpfCnpj: "116.519.536-46",
    telefone: "34999303434",
    email: null,
    endereco: "RUA ANTÔNIO REZENDE CHAVES Nº 554",
    bairro: "SANTA MONICA",
    cep: "38408-236",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "CLEYSON VINICIUS DE OLIVEIRA",
    cpfCnpj: "097.397.796-54",
    telefone: "34998660832",
    email: null,
    endereco: "RUA ALGODOEIRO DO CAMPO Nº 140",
    bairro: "INTEGRAÇÃO",
    cep: null,
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "DEYVISON ALVES DE OLIVEIRA",
    cpfCnpj: "045.478.596-80",
    telefone: "34991111918",
    email: null,
    endereco: "RUA ALDO PICCIGUELLI Nº 74",
    bairro: "JD PATRICIA",
    cep: "38414-158",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "EGUINALDO LOPES DE OLIVEIRA",
    cpfCnpj: "061.312.266-60",
    telefone: "34997803150",
    email: "leonardo4q@gmail.com",
    endereco: "AV CASTELA Nº 24 AP507 BL 3",
    bairro: "LARANJEIRAS",
    cep: "38410-727",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "FIDELES MARCOS JUVENCINO",
    cpfCnpj: "560.831.306-20",
    telefone: "34991384478",
    email: null,
    endereco: "RUA RESDE ATTIÊ Nº 120",
    bairro: "JD EUROPA",
    cep: null,
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "FRANCISCO RICARDO GUIMARAES SOUZA",
    cpfCnpj: "034.760.636-90",
    telefone: null,
    email: null,
    endereco: "AV ITAIPU Nº 657",
    bairro: "GRANADA",
    cep: "38410-538",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "GILMAR DIAS CARDOSO",
    cpfCnpj: "481.685.646-34",
    telefone: "34999708828",
    email: null,
    endereco: "RUA THOMAS EDWARD Nº 30",
    bairro: "JD HOLANDA",
    cep: null,
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "IZAIAS FERREIRA DA CRUZ",
    cpfCnpj: "111.791.596-40",
    telefone: "34998596222",
    email: null,
    endereco: "RUA MARIA CONCEIÇÃO LIMA Nº 121",
    bairro: "JD PROSPERIDADE",
    cep: "38407-571",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "LEANDRO BISPO MIRANDA",
    cpfCnpj: "019.847.776-39",
    telefone: "34998179358",
    email: null,
    endereco: "RUA DUNAS Nº 26",
    bairro: "MORUMBI",
    cep: "38407-390",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "MARCO TULIO ABRÃO DE CARVALHO",
    cpfCnpj: "060.115.896-26",
    telefone: "34991905059",
    email: null,
    endereco: "AL TERRAS ALTAS Nº 580",
    bairro: "JARDIN SUL",
    cep: null,
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "GRAZIO SI EMPREENDIMENTOS E CONSULTORIA LTDA",
    cpfCnpj: "22.959.515/0001-56",
    telefone: "34999712238",
    email: null,
    endereco: "RUA BERENICE REZENDE DINIS Nº 300 CASA 49",
    bairro: "MORADA DA COLINA",
    cep: "38411-162",
    cidade: "UBERLÂNDIA",
    estado: "MG",
  },
  {
    contratante: "Rones Almeida Melo",
    cpfCnpj: "448.807.588-04",
    telefone: "34996750937",
    email: null,
    endereco: "rua Antônio Mendes dos Santos 214",
    bairro: "granada",
    cep: null,
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "Liszandra Mendes Ferreira",
    cpfCnpj: "106.519.526-71",
    telefone: "34992820807",
    email: null,
    endereco: "Avenida Landscape",
    bairro: "Jardim Sul",
    cep: "38411-694",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "MAURÍCIO FLÁVIO FERNANDES",
    cpfCnpj: "073.494.606-60",
    telefone: "3499194-3260",
    email: null,
    endereco: "rua cupuaçu quadra 9 lote 25",
    bairro: "santa clara",
    cep: null,
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "RAUL SAIDE RESENDE",
    cpfCnpj: "112.770.826-00",
    telefone: "3499271-6880",
    email: null,
    endereco: "Rua dos Bambuzais 370",
    bairro: "Cidade Jardim",
    cep: "38412-114",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "CLÉSIO RIBEIRO DE ARAÚJO",
    cpfCnpj: "080.966.116-07",
    telefone: null,
    email: null,
    endereco: "Rua Professora Maria Célia Cence",
    bairro: "Shopping Park",
    cep: "38425-365",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    contratante: "TALVANE MOREIRA DE SOUZA",
    cpfCnpj: "058.688.216-29",
    telefone: "34984012352",
    email: null,
    endereco: "rua 07 número 50",
    bairro: "laranjeiras",
    cep: null,
    cidade: "Uberlândia",
    estado: "MG",
  },
];

const TODOS_EQUIPAMENTOS = [
  {
    nomeEquip: "BETONEIRA NORMALIZADA 400L",
    codigoEquip: "BET",
    precoDiaria: 100.0,
    precoSemanal: 150.0,
    precoQuinzenal: 250.0,
    precoMensal: 300.0,
    quantidadeDisp: 15,
    valorPatrimonio: 6200.0,
  },
  {
    nomeEquip: "GUINCHO DE COLUNA 200KG",
    codigoEquip: "GUIN",
    precoDiaria: 120.0,
    precoSemanal: 220.0,
    precoQuinzenal: 300.0,
    precoMensal: 450.0,
    quantidadeDisp: 7,
    valorPatrimonio: 5200.0,
  },
  {
    nomeEquip: "TALHA ELETRICA 300A 600KG",
    codigoEquip: "TALH",
    precoDiaria: 60.0,
    precoSemanal: 150.0,
    precoQuinzenal: 250.0,
    precoMensal: 300.0,
    quantidadeDisp: 1,
    valorPatrimonio: 1900.0,
  },
  {
    nomeEquip: "ROMPEDOR DE 25KG",
    codigoEquip: "RPG",
    precoDiaria: 120.0,
    precoSemanal: 400.0,
    precoQuinzenal: 600.0,
    precoMensal: 900.0,
    quantidadeDisp: 5,
    valorPatrimonio: 3500.0,
  },
  {
    nomeEquip: "ROMPEDOR DE 15KG",
    codigoEquip: "RPM",
    precoDiaria: 100.0,
    precoSemanal: 300.0,
    precoQuinzenal: 450.0,
    precoMensal: 700.0,
    quantidadeDisp: 3,
    valorPatrimonio: 1500.0,
  },
  {
    nomeEquip: 'ESMERILHADEIRA DE 7" POLEGADA',
    codigoEquip: "ESMG",
    precoDiaria: 60.0,
    precoSemanal: 120.0,
    precoQuinzenal: 200.0,
    precoMensal: 300.0,
    quantidadeDisp: 3,
    valorPatrimonio: 1400.0,
  },
  {
    nomeEquip: 'ESMERILHADEIRA DE 4"1/2 POLEGADA',
    codigoEquip: "ESM",
    precoDiaria: 50.0,
    precoSemanal: 90.0,
    precoQuinzenal: 120.0,
    precoMensal: 150.0,
    quantidadeDisp: 10,
    valorPatrimonio: 450.0,
  },
  {
    nomeEquip: "INVERSORA DE SOLDA BAMBOZZI 250A",
    codigoEquip: "INV",
    precoDiaria: 60.0,
    precoSemanal: 120.0,
    precoQuinzenal: 200.0,
    precoMensal: 300.0,
    quantidadeDisp: 3,
    valorPatrimonio: 2200.0,
  },
  {
    nomeEquip: "MARTELETE SDS PLUS MAKITA",
    codigoEquip: "MT",
    precoDiaria: 50.0,
    precoSemanal: 100.0,
    precoQuinzenal: 150.0,
    precoMensal: 250.0,
    quantidadeDisp: 12,
    valorPatrimonio: 1400.0,
  },
  {
    nomeEquip: 'SERRA MARMORE 7"1/8POLEGADA',
    codigoEquip: "SMG",
    precoDiaria: 80.0,
    precoSemanal: 150.0,
    precoQuinzenal: 200.0,
    precoMensal: 300.0,
    quantidadeDisp: 1,
    valorPatrimonio: 980.0,
  },
  {
    nomeEquip: "SERRA MARMORE",
    codigoEquip: "SM",
    precoDiaria: 40.0,
    precoSemanal: 80.0,
    precoQuinzenal: 100.0,
    precoMensal: 130.0,
    quantidadeDisp: 4,
    valorPatrimonio: 720.0,
  },
  {
    nomeEquip: "SERRA CIRCULAR",
    codigoEquip: "CIR",
    precoDiaria: 40.0,
    precoSemanal: 100.0,
    precoQuinzenal: 150.0,
    precoMensal: 250.0,
    quantidadeDisp: 5,
    valorPatrimonio: 1200.0,
  },
  {
    nomeEquip: "VIBRADOR DE CONCRETO COM MANGOTE 1,2 /2,5MTRS",
    codigoEquip: "VBR",
    precoDiaria: 80.0,
    precoSemanal: 150.0,
    precoQuinzenal: 200.0,
    precoMensal: 300.0,
    quantidadeDisp: 13,
    valorPatrimonio: 1400.0,
  },
  {
    nomeEquip: "LIXADEIRA GIRAFA",
    codigoEquip: "LXG",
    precoDiaria: 50.0,
    precoSemanal: 150.0,
    precoQuinzenal: 210.0,
    precoMensal: 350.0,
    quantidadeDisp: 3,
    valorPatrimonio: 980.0,
  },
  {
    nomeEquip: "LIXADEIRA DE MAO",
    codigoEquip: "LXM",
    precoDiaria: 40.0,
    precoSemanal: 100.0,
    precoQuinzenal: 150.0,
    precoMensal: 200.0,
    quantidadeDisp: 3,
    valorPatrimonio: null,
  },
  {
    nomeEquip: "AIRLESS",
    codigoEquip: "ARL",
    precoDiaria: 100.0,
    precoSemanal: 210.0,
    precoQuinzenal: 300.0,
    precoMensal: 400.0,
    quantidadeDisp: 1,
    valorPatrimonio: null,
  },
  {
    nomeEquip: "FURADEIRA DE IMPACTO",
    codigoEquip: "FR",
    precoDiaria: 40.0,
    precoSemanal: 80.0,
    precoQuinzenal: 100.0,
    precoMensal: 120.0,
    quantidadeDisp: 2,
    valorPatrimonio: 980.0,
  },
  {
    nomeEquip: "MOTO COMPRESSOR DE 26L",
    codigoEquip: "COMPR",
    precoDiaria: 80.0,
    precoSemanal: 150.0,
    precoQuinzenal: 200.0,
    precoMensal: 250.0,
    quantidadeDisp: 2,
    valorPatrimonio: 1400.0,
  },
  {
    nomeEquip: "BOMBA DE AGUA E ESGOTO COM MANGUEIRA DE 15MTRS",
    codigoEquip: "BOM",
    precoDiaria: 70.0,
    precoSemanal: 160.0,
    precoQuinzenal: 200.0,
    precoMensal: 250.0,
    quantidadeDisp: 2,
    valorPatrimonio: 1200.0,
  },
  {
    nomeEquip: "DESEMPENADEIRA DE MASSA E CONCRETO",
    codigoEquip: "DES",
    precoDiaria: 50.0,
    precoSemanal: 120.0,
    precoQuinzenal: 200.0,
    precoMensal: 250.0,
    quantidadeDisp: 1,
    valorPatrimonio: 450.0,
  },
  {
    nomeEquip: "SERRA POLICORTE",
    codigoEquip: "SPL",
    precoDiaria: 50.0,
    precoSemanal: 120.0,
    precoQuinzenal: 200.0,
    precoMensal: 250.0,
    quantidadeDisp: 1,
    valorPatrimonio: 1020.0,
  },
  {
    nomeEquip: "SERRA TICO-TICO",
    codigoEquip: "SERT",
    precoDiaria: 20.0,
    precoSemanal: 50.0,
    precoQuinzenal: 90.0,
    precoMensal: 120.0,
    quantidadeDisp: 1,
    valorPatrimonio: null,
  },
  {
    nomeEquip: "MARTELETE SDS 4,5KG",
    codigoEquip: "MTG",
    precoDiaria: 50.0,
    precoSemanal: 130.0,
    precoQuinzenal: 210.0,
    precoMensal: 300.0,
    quantidadeDisp: 1,
    valorPatrimonio: null,
  },
  {
    nomeEquip: "CHAVE DE IMPACTO",
    codigoEquip: "CHA",
    precoDiaria: 20.0,
    precoSemanal: 50.0,
    precoQuinzenal: 90.0,
    precoMensal: 120.0,
    quantidadeDisp: 2,
    valorPatrimonio: null,
  },
  {
    nomeEquip: "FURADEIRA A BATERIA",
    codigoEquip: "FRB",
    precoDiaria: 40.0,
    precoSemanal: 80.0,
    precoQuinzenal: 100.0,
    precoMensal: 130.0,
    quantidadeDisp: 1,
    valorPatrimonio: 980.0,
  },
  {
    nomeEquip: "ROCADEIRA DE 43MTRS",
    codigoEquip: "ROC",
    precoDiaria: 70.0,
    precoSemanal: 150.0,
    precoQuinzenal: 200.0,
    precoMensal: 250.0,
    quantidadeDisp: 2,
    valorPatrimonio: null,
  },
  {
    nomeEquip: "ROMPEDOR DE 7KG",
    codigoEquip: "RPP",
    precoDiaria: 80.0,
    precoSemanal: 150.0,
    precoQuinzenal: 200.0,
    precoMensal: 350.0,
    quantidadeDisp: 9,
    valorPatrimonio: 1040.0,
  },
  {
    nomeEquip: "EXTENSÃO 20MTRS",
    codigoEquip: "EXT",
    precoDiaria: 15.0,
    precoSemanal: 30.0,
    precoQuinzenal: 30.0,
    precoMensal: 30.0,
    quantidadeDisp: 11,
    valorPatrimonio: 250.0,
  },
  {
    nomeEquip: "SOPRADOR TÉRMICO",
    codigoEquip: "SPR",
    precoDiaria: 20.0,
    precoSemanal: 50.0,
    precoQuinzenal: 90.0,
    precoMensal: 120.0,
    quantidadeDisp: 1,
    valorPatrimonio: null,
  },
  {
    nomeEquip: "NÍVEL A LASER",
    codigoEquip: "NVL",
    precoDiaria: 50.0,
    precoSemanal: 80.0,
    precoQuinzenal: 100.0,
    precoMensal: 150.0,
    quantidadeDisp: 2,
    valorPatrimonio: 980.0,
  },
  {
    nomeEquip: "INVERSORA 160 A BAMBOZZI",
    codigoEquip: "INVP",
    precoDiaria: 50.0,
    precoSemanal: 100.0,
    precoQuinzenal: 150.0,
    precoMensal: 250.0,
    quantidadeDisp: 3,
    valorPatrimonio: 950.0,
  },
];

async function main() {
  console.log("🚀 Iniciando importação completa dos dados do SQL...\n");

  // Importar clientes
  let clientesImportados = 0;
  for (const cliente of TODOS_CLIENTES) {
    try {
      await prisma.cliente.upsert({
        where: { cpfCnpj: cliente.cpfCnpj },
        update: {},
        create: cliente,
      });
      clientesImportados++;
    } catch (error: any) {
      console.error(
        `Erro ao importar cliente ${cliente.contratante}:`,
        error.message,
      );
    }
  }

  console.log(`✅ ${clientesImportados} clientes importados`);

  // Importar equipamentos (verifica se já existe pelo código antes de criar)
  let equipamentosImportados = 0;
  for (const equip of TODOS_EQUIPAMENTOS) {
    try {
      const existente = await prisma.equipamento.findFirst({
        where: { codigoEquip: equip.codigoEquip },
      });

      if (!existente) {
        await prisma.equipamento.create({
          data: equip,
        });
        equipamentosImportados++;
      } else {
        // Atualiza o equipamento existente
        await prisma.equipamento.update({
          where: { id: existente.id },
          data: equip,
        });
        equipamentosImportados++;
      }
    } catch (error: any) {
      console.error(
        `Erro ao importar equipamento ${equip.nomeEquip}:`,
        error.message,
      );
    }
  }

  console.log(`✅ ${equipamentosImportados} equipamentos importados`);

  console.log("\n🎉 Importação completa concluída!");
  console.log(
    `📊 Total: ${clientesImportados} clientes, ${equipamentosImportados} equipamentos`,
  );
}

main()
  .catch((e) => {
    console.error("❌ Erro:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
